include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: true
    prefer_const_constructors: true
    require_trailing_commas: true
    always_use_package_imports: true
    prefer_const_constructors_in_immutables: true
    prefer_const_declarations: true
    use_to_and_as_if_applicable: true
    always_declare_return_types: true
