name: liveness_cam
description: Liveness camera for detecting fraud or detecting real person selfie
version: 0.0.7
homepage: https://kakzaki.dev

environment:
  sdk: ">=2.17.3 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.0+1
  google_mlkit_face_detection: ^0.9.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:

  plugin:
    platforms:
      android:
        package: id.kakzaki.liveness_cam
        pluginClass: LivenessCamPlugin
      ios:
        pluginClass: LivenessCamPlugin

